### ISSUE TITLE
Merge file recallcard_group.php and recallcard_lesson.php

### ISSUE THREAD

**Issue by sunboyy** [sunboyy/sb-learn#3]
The code in the file `recallcard_group.php` and `recallcard_lesson.php` shares similar functionality and UI. This causes code duplication and is difficult to maintain.

**Comment by nekoteoj** [comment]
I'll take a look on this. :)

**Comment by MarcinGladkowski** [comment]
Hi! I created some PR #8

**Comment by sunboyy** [comment]
Merged #8
