### ISSUE TITLE
Refactor: Decouple login logic

### ISSUE THREAD

**Issue by sunboyy** [sunboyy/sb-learn#4]
Currently, the login page is at `/src/login.php` which includes both presentation logic and back-end logic. This is bad in reusability. I am thinking of splitting this file into two files, one for front-end and the other for back-end.

### Things to do
- Create new file `/src/php/login.php` which handles logging in process
  - If method is not `POST`, returns 404
  - If logging in successful, set the session like how it is used to be and returns JSON `{"status": 1}`
  - If logging in failed, returns JSON `{"status": 0}`
- Remove all logging in process from `/src/login.php`
- When the form is submitted in `/src/login.php`, creates an HTTP request to the back-end file (you may use jQuery's built in function) and shows some loading indicator. If logging in succeeds, redirects the user to `index.php`. Otherwise, shows the error message `Incorrect Password` like how it is used to be. You can edit file `/src/js/login.js` if you want.

The list above is the guide make starting easier. However, I am open to other better solutions.

**Comment by akshay-achar** [comment]
@sunboyy : I am interested in working on this.

**Comment by sunboyy** [comment]
@akshayachar2011 Go for it!

**Comment by akshay-achar** [comment]
@sunboyy : Hi i have made the changes, can you give me permission to push the code to this repository. Thanks

**Comment by sunboyy** [comment]
@akshayachar2011 You can fork my project, commit and push to your repository and open a pull request to my repository. This allows you to have your code merged to my repository without me granting permission for you. This also allows me to review your code before merging your code too.

**Comment by akshay-achar** [comment]
> @akshayachar2011 You can fork my project, commit and push to your repository and open a pull request to my repository. This allows you to have your code merged to my repository without me granting permission for you. This also allows me to review your code before merging your code too.

Thanks @sunboyy . Will try on this.

**Comment by akshay-achar** [comment]
@sunboyy : I have created pull request https://github.com/sunboyy/sb-learn/pull/5. Can you check on this.

**Comment by sunboyy** [comment]
Resolved in 0f4a2c9
